cc_test(
    name = "test_transformation",
    srcs = ["test_transformation.cpp"],
    tags = ["unit"],
    deps = [
        "//src:object",
        "//src:transformation",
        "@gtest",
    ],
)
