cc_library(
    name = "object",
    srcs = ["Object.cpp"],
    hdrs = ["Object.h"],
    deps = ["@eigen"],
)

cc_library(
    name = "transformation",
    srcs = ["Transformation.cpp"],
    hdrs = ["Transformation.h"],
)
